config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  namespace :admin do
    resources :invoice_configurations
    get 'dashboard', to: 'dashboard#index'
    get 'event_importer', to: 'event_importer#index'
    resources :companies, except: :index
    resources :projects
    authenticate(:user) do
      resources :users do
        resources :projects
        resources :identities
        resources :pay_rates
        resources :pay_obligations
        get :user_data
        get :user_income
        get :user_permission
        post :user_permission
      end
    end
  end
  scope :identities do
    resources :remote_calendars
  end
  get 'edit_standard_workday', to: 'standard_workdays#edit'
  resources :standard_workdays
  get '/set_standard_work_day', to: 'set_standard_work_day#standard_workdays'
  resources :companies, except: :index
  namespace :message_api do
    get 'chatrooms', to: 'chatrooms#get_chatrooms'
    post 'login', to: 'messages#login'
    post 'chatroom/:chatroom_id', to: 'messages#create'
    get 'chatroom/:chatroom_id', to: 'messages#show'
  end
  get '/home', to: 'landing_page#index'
  get '/change_password', to: 'users#change_password'
  get 'current_user', to: 'user#edit'
  patch 'current_user', to: 'user#update'
  resources :travels
  namespace :projects do
    get 'time_sheet_for_week/show'
  end
  resources :vehicles do
    '#my-container'
    resources :travels
  end
  resources :pay_rates
  resources :identities
  resources :projects do
    resources :invoices, except: [:edit], controller: 'projects/invoices'
  end
  resources :invoices, except: [:edit]
  resources :works
  get '/send_invoice', to: 'invoices#send_invoice', as: :send_invoice
  resources :social_info
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  resources :time_sheets, as: :time_sheet_work_days
  resources :time_sheets do
    resources :travels
    collection do
      post 'hours_for_day/:date', to: 'time_sheets#hours_for_day', as: '_hours'
    end
  end

  get '/current_day/:time_period', to: 'days#index', as: :current_day
  get '/set_standard_work_hours', to: 'days#set_standard_work_hours'
  resources :customers do
    get :details
  end

  resources :projects do
    collection do
      get :all_work_for_project
      get '/hours_by_day/:id/', to: 'projects#hours_by_day', as: :hours_by_day
      get '/hours_by_user_by/:id', to: 'projects#hours_by_user', as: :hours_by_user
      get '/:id/time_sheets_for_week(.:format)', to: 'projects#time_sheets_for_week', as: :time_sheets_for_week
      # resources :time_sheets_for_week
    end
  end

  mount ActionCable.server => '/cable'

  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions',
               omniauth_callbacks: 'users/omniauth_callbacks'
               # passwords: 'users/passwords'
             }
  get 'auth/:provider/callback', to: 'time_sheet#index'

  root to: 'time_sheets#index'
  # root to: "landing_page#index"
end

app/models/project.rb
# frozen_string_literal: true

class Project < Record

  resourcify
  include Calculate
  include Defaults
  # has_many :invoices belongs_to :time_sheet
  attr_accessor :start_date, :end_date
  validates_presence_of :name
  has_many :time_sheets
  has_many :works
  belongs_to :customer
  belongs_to :user
  has_one :invoice_configuration
  has_rich_text :content

  def total_project_users(time)
    total = []
    time.each do |t|
      rate = t.user.rate(t.time_period.to_date)
      total << rate * t.hour rescue 0
    end
    total
  end

  def self.select_attributes
    result = []
    project = all.select(:id, :name).order(:created_at).reverse
    project.each do |p|
      result.append([p.name, p.id, { class: 'dropdown-item overflow-hidden' }])
    end
    result
  end

  #
  # def time_sheets_for_week(start_time, end_time)
  #
  #   # work.where()
  #
  #   time_sheets.includes(:works).where(time_period: start_time..end_time)
  #       .joins(:works).where('works.project_id = ?', id)
  #       .select('works.hour', 'works.project_id', :user_id, :time_period, :id, :invoice_id)
  #
  # end

  def hours_by_user_by_project
    TimeSheet.select(:id, :user_id).group(:user_id).where(project_id: id).select(:hour).sum(:hour)
  end

  def hours_by_date_range(start_time, end_time)
    TimeSheet.where(time_period: start_time..end_time).joins(:works).group(:time_period).where('works.project_id = ?', id).sum(:hour)
  end

  def hours_by_day
    TimeSheet.includes(:project).group(:time_period).where('project_id = ?', id).sum(:hour)
  end

  def all_time_sheets
    TimeSheet.where('project_id = ?', id)
  end

  def info_for_invoice_range(start_time, end_time)
    TimeSheet.where(time_period: start_time..end_time)
             .joins(:work).group(:time_period)
             .where('works.project_id = ?', id)
             .sum(:hour)
  end
end

app/controllers/admin/projects_controller.rb
# frozen_string_literal: true

class Admin::ProjectsController  < AdminController
  before_action :set_project, only: %i[show edit update destroy hours_by_day hours_by_date_range hours_by_user time_sheets_for_week]
  before_action :authenticate_user!
  load_and_authorize_resource
  require 'github'

  def index
    @projects = Project.all.paginate(page: params[:page], per_page: 10).reverse_order
    @project = Project.new

    auth = current_user.identities.find_by(provider: 'github').token rescue nil
    repos = repos(auth)
    @repo_list = repos.map do |r|
      [r['name'], r['id']]
    end

  end

  # GET /projects/1
  def show
    @start_date = params[:start_date] || Date.current.beginning_of_month
    @end_date = params[:end_date] || Date.current.end_of_month
    @time = TimeSheet::WorkDay.where(time_period: @start_date..@end_date, project: @project).order(:time_period)
    @time = @time.where(user_id: params[:user_id]) if params[:user_id].present?

    respond_to do |format|
      format.html {
        @column_chart = @time.group(:time_period).sum(' finish_time - start_time ')

        @users = @project.company.users
        @chat = @project.hours_by_day
        @time = @time.paginate(page: params[:page], per_page: 20)
      }
      format.csv { send_data @time.to_csv }
      format.xlsx{
        @grouped_by_user = @time.group_by &:user
      }
      format.pdf do
        render pdf: 'Invoice', header: { right: '[page] of [topage]' }
      end
      format.js {
        @column_chart = @project.hours_by_day
        @time = @time.paginate(page: params[:page], per_page: 20)
      }
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    auth = current_user.identities.find_by(provider: 'github').token rescue nil
    repos = repos(auth)
    @repo_list = repos.map { |r| [r['full_name'], r['id']] }
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to admin_projects_path, notice: 'Project was successfully created.' }
        format.js
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /projects/1
  def update
    respond_to do |format|
      # authorize @project
      if @project.update(project_params)
        format.html { redirect_to [:admin,@project], notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to admin_projects_url, notice: 'Project was successfully destroyed.' }
    end
  end

  def hours_by_day
    @start_date = params[:start_date] || Date.current.beginning_of_month
    @end_date = params[:end_date] || Date.current.end_of_month
    render json: @project.hours_by_date_range(@start_date, @end_date)
  end

  def hours_by_user
    render json: @project.hours_by_user_by_project
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :start_date, :end_date, :customer_id)
  end

  # def user_not_authorized(exception)
  #   policy_name = exception.policy.class.to_s.underscore
  #
  #   flash[:error] = t "#{policy_name}.#{exception.query}", scope: "pundit", default: :default
  #   redirect_to(request.referrer || root_path)
  # end

  def repos(auth)
    repo_list = ['error']
    url = URI.parse("https://api.github.com/user/repos")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    req = Net::HTTP::Get.new(url.request_uri)
    req["Accept"] = 'application/vnd.github.cloak-preview'
    req["Authorization"] = "token #{auth}" if auth.present?
    res = http.request(req)
    repo_list = JSON.parse(res.body) if res.message == "OK"
    repo_list
  end

end

app/controllers/projects/invoices_controller.rb
# frozen_string_literal: true

class Projects::InvoicesController < ProjectsController


  before_action :set_invoice, only: %i[show edit update destroy]
  before_action :authenticate_user!
  load_and_authorize_resource only: %i[index show new]
  skip_authorization_check only: %i[edit create]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.where(project_id: params[:project_id], user_id: current_user.id).paginate(page: params[:page], per_page: 10).reverse_order
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @row_total = @invoice.total_for_user
    @total = @invoice.invoice_total(@row_total)
    @works = @invoice.time_sheets.order(:time_period)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "invoice_#{@invoice.id}_#{@invoice.user.first_name}_#{@invoice.user.last_name}_#{@works.first.time_period.strftime('%d-%m-%Y')}_#{@works.last.time_period.strftime("%d-%m-%Y")}",
               header: {right: '[page] of [topage]'},
               page_size: 'A4',
               dpi: 900,
               margin: {
                   top: 0,
                   bottom: 0,
                   left: 0,
                   right: 0}

      end
    end
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    if params[:search]
      @project = Project.find(params[:search])
      @invoice = Invoice.new
      @work = @project.time_sheets.order(:time_period).where(invoice_id: nil)
      @total_for_user = @invoice.total_for_users(@work)
      @total = @invoice.total(@total_for_user)

      respond_to do |format|
        format.js
        format.html
      end

    else
      @project = Project.first
      @work = TimeSheet.uninvoiced_work(@project&.id)
      @total_for_user = @invoice.total_for_users(@work)
      @total = @invoice.total(@total_for_user)

    end
  end

  # GET /invoices/1/edit
  def edit;
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new
    # @invoice.user = current_user
    @invoice = @invoice.save_invoice(invoice_params[:project])

    respond_to do |format|
      if @invoice.save

        format.html {redirect_to invoice_path(@invoice), notice: 'Invoice was successfully created.'}
        format.js
        format.pdf

      else
        format.html {redirect_to new_invoice_path, notice: 'Invoice is empty so not saved.'}
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html {redirect_to @invoice, notice: 'Invoice was successfully updated.'}
        format.json {render :show, status: :ok, location: @invoice}
      else
        format.html {render :edit}
        format.json {render json: @invoice.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html {redirect_to invoices_url, notice: 'Invoice was successfully destroyed.'}
      format.json {head :no_content}
    end
  end


  def send_invoice

    invoice = params[:invoice]
    InvoiceMailer.invoice_email(invoice).deliver_later
    flash[:notice] = 'Invoice  sent!'
    redirect_to invoice_path(invoice)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def invoice_params
    # puts params.to_yaml
    params.require(:invoice).permit(:id, :search, :name, :endOfFortnight, :invoice_id, :project, :search, invoice_rows_attributes: %i[id rate hours project_id created_at update_at])
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy hours_by_day hours_by_date_range hours_by_user time_sheets_for_week]
  before_action :authenticate_user!
  load_and_authorize_resource
  require 'github'

  def index
    @projects = Project.all.paginate(page: params[:page], per_page: 10).reverse_order
    @project = Project.new

    # auth = current_user.identities.find_by(provider: 'github').token rescue nil
    # repos = repos(auth)
    # @repo_list = repos.map do |r|
    #   [r['name'], r['id']]
    # end

  end

  # GET /projects/1
  def show
    @start_date = params[:start_date] || Date.current.beginning_of_month
    @end_date = params[:end_date] || Date.current.end_of_month
    @time = TimeSheet::WorkDay.where(time_period: @start_date..@end_date, project: @project).order(:time_period)
    @time = @time.where(user_id: params[:user_id]) if params[:user_id].present?

    respond_to do |format|
      format.html {
        @column_chart = @time.group(:time_period).sum(' finish_time - start_time ')

        @users = @project.company.users
        @chat = @project.hours_by_day
        @time = @time.paginate(page: params[:page], per_page: 20)
      }
      format.csv { send_data @time.to_csv }
      format.xlsx{
        @grouped_by_user = @time.group_by &:user
      }
      format.pdf do
        render pdf: 'Invoice', header: { right: '[page] of [topage]' }
      end
      format.js {
        @column_chart = @project.hours_by_day
        @time = @time.paginate(page: params[:page], per_page: 20)
      }
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.content = "<h1>Customise Your Project's Homepage</h1><br>This is a good place for your projects description"
  end

  # GET /projects/1/edit
  def edit
    auth = current_user.identities.find_by(provider: 'github').token rescue nil
    repos = repos(auth)
    @repo_list = repos.map { |r| [r['full_name'], r['id']] }
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.js
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /projects/1
  def update
    respond_to do |format|
      # authorize @project
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
    end
  end

  def hours_by_day
    @start_date = params[:start_date] || Date.current.beginning_of_month
    @end_date = params[:end_date] || Date.current.end_of_month
    render json: @project.hours_by_date_range(@start_date, @end_date)
  end

  def hours_by_user
    render json: @project.hours_by_user_by_project
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :start_date, :end_date, :customer_id,:content)
  end

  # def user_not_authorized(exception)
  #   policy_name = exception.policy.class.to_s.underscore
  #
  #   flash[:error] = t "#{policy_name}.#{exception.query}", scope: "pundit", default: :default
  #   redirect_to(request.referrer || root_path)
  # end

  def repos(auth)
    repo_list = ['error']
    url = URI.parse("https://api.github.com/user/repos")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    req = Net::HTTP::Get.new(url.request_uri)
    req["Accept"] = 'application/vnd.github.cloak-preview'
    req["Authorization"] = "token #{auth}" if auth.present?
    res = http.request(req)
    repo_list = JSON.parse(res.body) if res.message == "OK"
    repo_list
  end

end

app/views/admin/projects/_column_chart.html.erb
<%= column_chart @column_chart %>

app/views/admin/projects/_form.html.erb
<div class="container">
  <div class="form-horizontal">
    <%= form_for([:admin,project], remote: true) do |f| %>
      <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% @project.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <div class="row">
          <div class="col-sm-1">
            <%= f.label :name, class: "control-label" %>
          </div>
          <div class=" col-sm-7">
            <%= f.text_field :name, class: "form-control", :autofocus => true %>
          </div>
        </div>
      </div>
      <div class="form-group">

        <div class="row">
          <div class="col-sm-1">
            <%= f.label :customer, class: "control-label" %>
          </div>
          <div class=" col-sm-7">
            <%= f.select(:customer_id, Customer.all.collect { |c| [c.full_name, c.id] }, {}, class: 'btn btn-default') %>
          </div>
        </div>
        <div class="row-li">
          <div class="col-sm-1">
            <%#= f.label :gitname, class: "control-label" %>
          </div>
<!--          <div class="col-sm-5">-->
            <%#= f.select(:gitname, options_for_select(@repo_list, params[:gitname]), class: 'btn btn-default form-control') %>
<!--          </div>-->
          <div class="col-sm-12" style="text-align: right">
            <%= f.submit class: "btn btn-default" %>
          </div>
        </div>
        <div>
        </div>
    <% end %>
    </div>
  </div>

app/views/admin/projects/_project.html.erb
<li class="shadow clickable project-<%= project.id %>">
<div class="row-li">
  <div class="col-md-5 col-xs-5">
    <h5 class="clickable"> <%= project.name.humanize %></h5>
  </div>
  <div class="col-md-5 col-xs-5">
    <h5>
      <% if project.customer.present? %>
        <%= project.customer.full_name %>
      <% else %>
        <%= 'No Customer Selected' %>
      <% end %>
    </h5>

    <%= link_to 'Show',[:admin, project], class: "hidden" %>
  </div>
  <div class="col-md-1 col-xs-1 user">
    <%= link_to  [:admin,project], data: { confirm: "Are you sure"},method: :delete do %>
        <i class="far fa-trash-alt fa-lg" aria-hidden="true"></i>
    <%end %>
  </div>
</div>

</li>

app/views/admin/projects/_time_sheets_for_week.html.erb
<div class="table-responsive">
  <table class="table outline table-striped table-hover">
    <div id="page_links">
      <%#= will_paginate @time %>
    </div>
    <tr class=" grey_background">
      <th>User Name</th>
      <th>Date worked</th>
      <th>Start Time</th>
      <th>Finish Time</th>
      <!--      <th>Rate</th>-->
      <th>HH:MM</th>
      <th>Description</th>
      <!--      <th>Sub Total</th>-->

    </tr>
    <% total = 0 %>
    <% time.each_with_index do |time, i| %>

      <tr>
        <% if time.type == 'TimeSheet::WorkDay' %>
        <td><%= link_to "#{time.user.full_name}", edit_time_sheet_path(time) %></td>
          <% else %>
          <td><%= time.user.full_name %></td>
          <% end %>
        <td><%= time.time_period.strftime("%d/%m/%y ") %></td>
        <td><%= time&.start_time&.strftime('%H:%M') %></td>
        <td><%= time&.finish_time&.strftime('%H:%M') %></td>
        <td>
          <% if time&.finish_time.present? &&  time&.start_time.present? %>
          <% hour = time.finish_time - time.start_time %>
            <% else %>
            <% hour = 0 %>
            <% end %>
          <% total = total + hour %>
          <%= Time.at(hour).utc.strftime("%H:%M") %>
        </td>
        <td><%= time.description %></td>
      </tr>

    <% end %>
    <tr>

      <td></td>
      <td></td>
      <td></td>
      <td></td>


      <td>Total Hours <%= (total / 60 /60 ).round(2)%>
      <td></td>
      </td>

    </tr>
  </table>
  <div id="page_links">
    <%= will_paginate time %>
  </div>
</div>

app/views/admin/projects/create.js.erb
$('#book-list').prepend('<%=j render  @project %>');
$("#show-form").trigger('reset');
$(".message-form").slideUp();

app/views/admin/projects/edit.html.erb
<div class="box">
<div id="flash">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>


<h1>Editing Project</h1>
<!--</div><div class="box">-->
  <%#= link_to 'Show', @project,class: 'btn btn-default' %>
  <%#= link_to 'Back', admin_projects_path,class: 'btn btn-default' %>
<!--</div>-->
</div>
<div class="box">

  <%= render 'form', project: @project %>
</div>

app/views/admin/projects/index.html.erb
<div class="box">
  <div class="container-fluid">

    <div class="row">
<!--      <div class='pull-right'>-->
        <%#= link_to 'New Project',admin_ %>
<!--        <button id="new-project" class="btn btn-primary">New Project</button>-->
<!--      </div>-->
      <h1>Projects</h1>
<!--      <div>-->
<!--          <NewProject id="NewProject" class="new-project">-->

            <%#= render 'form' %>

<!--          </NewProject>-->
<!--        </div>-->
      </div>
    </div>
  </div>




  <%= will_paginate @projects %>
  <ul class="list-clickable">

      <%= render partial:'admin/projects/project', collection: @projects %>
  </ul>
  <%= will_paginate @projects %>


</div>



</div>

app/views/admin/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/show.html.erb
<div class=" box">
  <h1><%= @project.name.capitalize %></h1>
  <h2>Total hours for project <%= Work.total_hours_for_project(@project&.id) %></h2>

</div>
<!--<div class="box">-->
<!--  <div class="btn-group">-->
    <%= link_to 'Edit', edit_admin_project_path(@project), class: 'btn btn-default top-right' %>
    <%#= link_to 'Back', admin_projects_path, class: 'btn btn-default' %>
    <%#= link_to 'GitHub', social_info_index_path(project: @project), class: 'btn btn-default' %>
    <%#= link_to 'Invoices', project_invoices_path(project_id: @project&.id), class: 'btn btn-default' %>
<!--  </div>-->
<!--</div>-->

<div class="box">
  <%= form_tag project_path(@project), method: :get do %>
    <div class="row">
      <div class="btn-group" style="margin-left: 15px">
        <button formaction=" <%= project_path(@project, format: 'csv') %>" ,type="submit" , class="btn btn-default">Csv</button>
        <button formaction=" <%= project_path(@project, format: 'xlsx') %>" ,type="submit" , class="btn btn-default">Excel</button>
        <%= submit_tag "search", class: "btn btn-default " %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-4">
        <%= label_tag :start_date %>
        <%= date_field_tag :start_date, Date.current.beginning_of_month, class: "form-control" %>
        <%= label_tag :end_date %>
        <%= date_field_tag :end_date, Date.current.end_of_month, class: "form-control " %>

      </div>
    </div>
    </div>
    <div>
    <div class="box">


      <div >
        <% @users.each do |user| %>
          <%= link_to user.full_name, project_path(@project, user_id: user.id), class: 'btn btn-default', remote: true %>
        <% end %>
        <%= link_to 'All Users', project_path(@project), class: 'btn btn-default', remote: true %>
      </div>
      <div id='timesheet-for-weeks' style="margin: 15px">
        <%= render 'time_sheets_for_week', time: @time %>
      </div>
  <% end %>
    </div>
    <div class="box">
      <h1>Hours By Day</h1>
     <div id='column-chart'> <%= render 'column_chart' %></div>
    </div>
    <div class="box">
      <h1>Users Hours For This Project</h1>
<!--     <div id="pie-chart">-->
       <%= pie_chart hours_by_user_projects_path(@project,user_id: params[:user_id]) %>
<!--     </div>-->

    </div>


</div>

app/views/admin/projects/show.js.erb
$('.pagination a').attr('data-remote', 'true');
$('#timesheet-for-weeks').html('<%= j render 'time_sheets_for_week', time: @time %>')

app/views/admin/projects/show.pdf.erb
<html>
<head>
  <script>
      function number_pages() {
          var vars = {};
          var x = document.location.search.substring(1).split('&');
          for (var i in x) {
              var z = x[i].split('=', 2);
              vars[z[0]] = decodeURIComponent(z[1]);
          }
          var x = ['frompage', 'topage', 'page', 'webpage', 'section', 'subsection', 'subsubsection'];
          for (var i in x) {
              var y = document.getElementsByClassName(x[i]);
              for (var j = 0; j < y.length; ++j) y[j].textContent = vars[x[i]];
          }
      }
  </script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= wicked_pdf_stylesheet_link_tag "pdf" -%>

<body onload="number_pages()" class="pdf-background">
<div class="alwaysbreak">
  <table style="width: 100%; ">
    <tr class="pdf-tr ">
      <td><h1>Tax Invoice</h1>
      </td>
      <td pdf-tr>
        <div align="right" style="padding: 10">
          <h3>For time period</h3>
          <%= @time.first.time_period.strftime("%A %b %d ") %>|
          <%= Date.today.strftime("%A %b %d") %>
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <h2>to: <%= @project.customer.full_name %></h2>
        <p><%= @project.customer.address %> <br>
          ABN: <%= @project.customer.abn %></p>

        <p>
        <h2><%= current_user.full_name %> </h2>
        <%= current_user.address %> <br>
        ABN: <%= current_user.abn %></p>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <div id="">
          <%= render 'shared/time_sheets_for_week.html.erb', time: @time, :formats => [:html] %>
        </div>

    <tr>
      <td>Please pay you invoice with in 2 week or men with guns will come to you house and take possession of you dog
      </td>
    </tr>
  </table>

</div>
</body>
</html>

app/views/admin/projects/w.xlsx.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Employee</Data></Cell>
        <Cell><Data ss:Type="String">Date</Data></Cell>
        <Cell><Data ss:Type="String">Pay rate</Data></Cell>
        <Cell><Data ss:Type="String">Hours</Data></Cell>
      </Row>
      <% @time.each_with_index do |time, i | %>
          <Row>
            <Cell><Data ss:Type="String"><%= "#{time.user.full_name}"  %></Data></Cell>
            <Cell><Data ss:Type="String"><%= time.time_period.strftime("%A %b %d ") %></Data></Cell>
            <Cell><Data ss:Type="String"><%= time.user.rate(time.time_period) %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= time.hour %></Data></Cell>
          </Row>
      <% end %>
      <Row>
        <Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String">total hours <%= @project.sum_time_sheet(@time)%></Data></Cell>
      </Row>
    </Table>
  </Worksheet>
</Workbook>