config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  namespace :admin do
    resources :invoice_configurations
    get 'dashboard', to: 'dashboard#index'
    get 'event_importer', to: 'event_importer#index'
    resources :companies, except: :index
    resources :projects
    authenticate(:user) do
      resources :users do
        resources :projects
        resources :identities
        resources :pay_rates
        resources :pay_obligations
        get :user_data
        get :user_income
        get :user_permission
        post :user_permission
      end
    end
  end
  scope :identities do
    resources :remote_calendars
  end
  get 'edit_standard_workday', to: 'standard_workdays#edit'
  resources :standard_workdays
  get '/set_standard_work_day', to: 'set_standard_work_day#standard_workdays'
  resources :companies, except: :index
  namespace :message_api do
    get 'chatrooms', to: 'chatrooms#get_chatrooms'
    post 'login', to: 'messages#login'
    post 'chatroom/:chatroom_id', to: 'messages#create'
    get 'chatroom/:chatroom_id', to: 'messages#show'
  end
  get '/home', to: 'landing_page#index'
  get '/change_password', to: 'users#change_password'
  get 'current_user', to: 'user#edit'
  patch 'current_user', to: 'user#update'
  resources :travels
  namespace :projects do
    get 'time_sheet_for_week/show'
  end
  resources :vehicles do
    '#my-container'
    resources :travels
  end
  resources :pay_rates
  resources :identities
  resources :projects do
    resources :invoices, except: [:edit], controller: 'projects/invoices'
  end
  resources :invoices, except: [:edit]
  resources :works
  get '/send_invoice', to: 'invoices#send_invoice', as: :send_invoice
  resources :social_info
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  resources :time_sheets, as: :time_sheet_work_days
  resources :time_sheets do
    resources :travels
    collection do
      post 'hours_for_day/:date', to: 'time_sheets#hours_for_day', as: '_hours'
    end
  end

  get '/current_day/:time_period', to: 'days#index', as: :current_day
  get '/set_standard_work_hours', to: 'days#set_standard_work_hours'
  resources :customers do
    get :details
  end

  resources :projects do
    collection do
      get :all_work_for_project
      get '/hours_by_day/:id/', to: 'projects#hours_by_day', as: :hours_by_day
      get '/hours_by_user_by/:id', to: 'projects#hours_by_user', as: :hours_by_user
      get '/:id/time_sheets_for_week(.:format)', to: 'projects#time_sheets_for_week', as: :time_sheets_for_week
      # resources :time_sheets_for_week
    end
  end

  mount ActionCable.server => '/cable'

  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions',
               omniauth_callbacks: 'users/omniauth_callbacks'
               # passwords: 'users/passwords'
             }
  get 'auth/:provider/callback', to: 'time_sheet#index'

  root to: 'time_sheets#index'
  # root to: "landing_page#index"
end

app/models/time_sheet.rb
# frozen_string_literal: true

require "csv"
require "google_calendar"
class TimeSheet < Record
  include Defaults
  include Calculate
  resourcify
  # validates_presence_of :time_period, :hour
  has_many :travels, dependent: :destroy
  accepts_nested_attributes_for :travels, allow_destroy: true
  # has_many :works, dependent: :destroy
  belongs_to :project
  belongs_to :invoice, required: false
  # accepts_nested_attributes_for :works, allow_destroy: true, :reject_if => lambda {|a| a[:hour].blank?}
  # validates_presence_of :time_period
  belongs_to :user
  has_many :works, dependent: :destroy
  scope :date_range, ->(start_date, end_date) { where(time_period: start_date..end_date) }
  scope :for_project, ->(project) { where(projects: project) }
  # validates_presence_of :description
  before_validation :set_hours
  def self.to_csv(options = {})
    ::CSV.generate(options) do |csv|
      csv << ["user_name", "date Worked", "hours", "rate"]
      all.each do |p|
        csv << [p.user.full_name, p.time_period, p.hour, p.user.rate(p.time_period)]
      end
    end
  end

  def has_invoice?
    invoice_id.present?
  end

  def hour
    self[:hour] / 3600 rescue 0
  end

  def self.uninvoiced_work(project_id)
    # select(:hour, :id, :time_sheet_id)
    where("invoice_id IS ?", nil)
  end

  def self.filter_buy_date(start_date, end_date)
    where("time_period \tBETWEEN ? AND ? ", start_date.to_s, end_date.to_s)
  end

  # def self.has_time_sheet(day, user)
  #   Work.joins(:time_sheet).where('time_sheets.time_period = ?', day).where('time_sheets.user_id =?', user).exists?
  # end

  # def has_time_sheet?
  #   # Work.joins(:time_sheet).where('time_sheets.time_period = ?', day).where('time_sheets.user_id =?', user).exists?
  #   self.present?
  # end

  def self.for_project(project)
     project.time_sheets
  end

  def set_hours
    # hour =  finish_time - start_time
    self.hour = if finish_time.present? && start_time.present? && finish_time > start_time
      finish_time - start_time
    else
      0
    end
  end
end

app/models/time_sheet/holiday.rb
class TimeSheet::Holiday < TimeSheet
end

app/models/time_sheet/public_holiday.rb
class TimeSheet::PublicHoliday < TimeSheet
end

app/models/time_sheet/rdo.rb
class TimeSheet::Rdo < TimeSheet
end

app/models/time_sheet/work_day.rb
class TimeSheet::WorkDay < TimeSheet
end

app/controllers/time_sheets_controller.rb
# frozen_string_literal: true

class TimeSheetsController < ApplicationController
  before_action :set_time_sheet, only: %i[ edit update destroy]
  before_action :authenticate_user!

  require 'github'

  load_and_authorize_resource
  # before_action :set_calender, only: :index
  # GET /time_sheets
  # GET /time_sheets.json

  add_breadcrumb 'home', :root_path
  add_breadcrumb 'my', :time_sheets_path

  # def travel
  #   @travel = TimeSheet.find(params[:time_sheet_id])
  #   @travel.travels.build if @travel.travels.count < 1
  #   @travel.user = current_user
  #   respond_to do |format|
  #     format.js
  #     format.html
  #   end
  # end

  def index
    @user = current_user
    @project ||= Project.find(params[:project_id]) rescue Project.first
    @time_sheets = @user&.time_sheets&.where(project_id: @project&.id)

  end

  # GET /time_sheets/1
  # GET /time_sheets/1.json
  def show
    @project = Project.first
    @project = Project.find params[:project_id] if params[:project_id].present?
    @time_sheet = TimeSheet::WorkDay.find_or_initialize_by(id: params[:id])

    # options = {}
    # @github = []
    # @time_sheet.works.build if @time_sheet.works.count < 1
    # options[:token] = current_user.identities.find_by(provider: 'github').token rescue ''
    # day = @time_sheet.time_period

    # github = Github.new(options)

    # @time_sheet.projects.each {|project| @github << {name: project.name, data: github.commit_on_day(day, project.gitname, project.branch, current_user.email)} if project.present?}

    # @github = @project.each { |project| Github.new(project.gitname, options).commit_on_day}
  end

  #
  # def current_day
  #   @time_sheet = TimeSheet.find_or_create_by(time_period: params[:time_period], user: current_user,project_id: params[:project_id])
  #   if @time_sheet.id.nil?
  #     @time_sheet.time_period = params[:time_period]
  #     @time_sheet.user = current_user
  #     @time_sheet.save!
  #   end
  #   redirect_to time_sheet_path(@time_sheet)
  # end

  # GET /time_sheets/new
  def new
    @time_sheet = TimeSheet::WorkDay.new
    @time_sheet.works.build
    @time_sheet.user = current_user
    @time_sheet.description = @time_sheet.description.present? ? @time_sheet.description : "#{@time_sheet.user.full_name} Hour's"

  end

  # GET /time_sheets/1/edit
  def edit
    @user = current_user
    @time_sheet = TimeSheet::WorkDay.find(params[:id])
    @time_sheet.description = @time_sheet.description.present? ? @time_sheet.description : "#{@time_sheet.user.full_name} Hour's"

    # @time_sheet.works.build if @time_sheet.works.count < 1event_importers
    respond_to do |format|
      format.js
      format.html
    end
  end

  # POST /time_sheets
  # POST /time_sheets.json
  def create
    @time_sheet = TimeSheet::WorkDay.new(time_sheet_params)
    @time_sheet.user = current_user

    respond_to do |format|
      if @time_sheet.save
        set_event_in_google_calendar
        format.html { redirect_to root_path(project_id: @time_sheet.project_id), notice: 'Time sheet was successfully created.' }
        format.json { render :index, status: :created, location: @time_sheet }
        format.js { redirect_to root_path(project_id: @time_sheet.project), notice: 'Time sheet was successfully created.' }
      else
        # format.html { redirect_to current_day_path(@time_sheet.time_period,@time_sheet.project ) }
        format.json { render json: @time_sheet.errors, status: :unprocessable_entity }
        format.js { params[:project_id] = @time_sheet.project_id, params[:time_period] = @time_sheet.time_period }
        format.html
      end
    end
  end

  # PATCH/PUT /time_sheets/1
  # PATCH/PUT /time_sheets/1.json
  def update
    respond_to do |format|
      if @time_sheet.update(time_sheet_params)
        set_event_in_google_calendar
        format.html { redirect_to root_path(project_id: @time_sheet.project_id), notice: 'Time sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_sheet }

      else
        format.html { render :show }
        format.json { render json: @time_sheet.errors, status: :unprocessable_entity }
        format.js { params[:id] = @time_sheet.id, params[:project_id] = @time_sheet.project_id, params[:time_period] = @time_sheet.time_period }
      end
    end
  end

  # DELETE /time_sheets/1
  # DELETE /time_sheets/1.json
  def destroy
    EventImporter.where(time_sheet_id: @time_sheet.id).destroy_all
    @time_sheet.destroy
    respond_to do |format|
      format.html { redirect_to time_sheets_url, notice: 'Time sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def hours_for_day
    @hours = TimeSheet::WorkDay.where(date: params[:date]).joins(:works).select(:hour)
    respond_to do |format|
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event_in_google_calendar
    google = @current_user.google_auth_token
    if google.present? && google&.remote_calendar&.remote_system_id&.present?
      @auth = google.token
      @cal = GoogleCalendar.new(token: @auth)
      Time.zone = 'Brisbane'
      timestamp = DateTime.current
      @cal.update_or_create_event(calendar_id: google&.remote_calendar&.remote_system_id, attendee: google.email, summary: @time_sheet.description, start_time: DateTime.parse(@time_sheet.start_time.to_s).to_s, end_time: DateTime.parse(@time_sheet.finish_time.to_s).to_s, timezone: ActiveSupport::TimeZone[timestamp.utc_offset].tzinfo.name)
    end
  end

  def set_calender

  end

  def set_time_sheet
    # @time_sheet = TimeSheet.includes(:user).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def time_sheet_params
    params.require(:time_sheet_work_day).permit(:time_period, :user_id, :start_time, :finish_time, :description, :hour, :project_id)
    # works_attributes: %i[id date hour description project_id time_sheet_id _destroy],
    # travels_attributes: %i[id travel_date od_start od_finish purpose user_id project_id time_sheet_id vehicle_id])
  end
end

app/helpers/time_sheets_helper.rb
# frozen_string_literal: true

module TimeSheetsHelper
  def my_calendar(options = {}, &block)
    raise 'month_calendar requires a block' unless block_given?
    MyCalendar.new(self, options).render(&block)
  end

  def get_duration_hrs_and_mins(duration)
    hours = duration / (3600000 * 3600000)
    minutes = (duration / 60000) % 60000
    "#{hours.round(2)}h #{minutes.round(2)}m"
  rescue
    ""
  end
end

app/views/time_sheets/_commits.html.erb
<table>

  <tr>
    <th>Commit</th>
    <th>Date</th>
    <th>Project</th>
    <th>Link</th>
  </tr>
  <% @github.each do |project| %>
    <% project[:data].each do |v| %>
    <tr>

      <td>  <%= v['commit']['message'] %></td>
      <td>  <%= Time.parse(v['commit']['author']['date']).strftime("%A %b/%d/%Y") %></td>
      <td><%= project[:name] %></td>
      <td>  <%= link_to 'GO TO', v['html_url'], class: 'btn btn-default' %></td>

    </tr>
  <% end %>
  <% end %>

</table>

app/views/time_sheets/_errors.html.erb
<div class="actions">
  <% if @time_sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_sheet.errors.count, "error") %> prohibited this time_sheet from being saved:</h2>

      <ul>
        <% @time_sheet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/time_sheets/_finish_button.html.erb
<%= react_component("StartTimeButton",
    props={ name: "time_sheet_work_day[#{name}]",
             initial_time: time , time_period: params[:time_period] ,id: name},
  html_options={prerender: true}) %>

app/views/time_sheets/_form.html.erb
<%= form_for(@time_sheet, remote: true, style: 'position: relative') do |f| %>
  <div id='errors'></div>

  <table class="outline table table-striped table-hover outline " style="  outline: 2px solid #ccc;">
    <tr class="grey_background " id="hours">
      <th style="width: 20%">Start Time</th>
      <th style="width:20%">Finish Time</th>
      <th style="width: 20%">HH:MM</th>
      <th class="small-screen-hide" style="width: 10%"> Invoiced</th>
    </tr>
    <tr style="padding: 0;">
      <% if @time_sheet.invoice_id? %>

        <td colspan="5" class="clickable  " style="margin-bottom: 0px; outline: 2px solid #ccc;">
          <div class="row-li " style="display:flex; flex-direction: row">
            <div class="cell">
              <%= @time_sheet.project.name %>
            </div>
            <div class="cell">
              <%= @time_sheet.start_time&.strftime('%d/%m/%y %I:%M  %p') || 'Not Set' %>
            </div>
            <div class="cell">
              <%= @time_sheet.finish_time&.strftime('%d/%m/%y %I:%M  %p') || 'Not Set' %>
            </div>
            <div class="cell">
              <%= @time_sheet.hour.round(2) %>
            </div>
            <div class="cell small-screen-hide">
              <%= image_tag('tick.png', size: "40x40") %>
            </div>
            <div class="field col-xs-11 col-sm-4" style='padding: 0%'>
              <%= @time_sheet.description %>
            </div>
            <div class="field col-xs-1 col-sm-1">
              <%= link_to "", invoice_path(@time_sheet.invoice_id) %>
            </div>
          </div>
        </td>
        </tr>
        <tr>
          <td colspan="4">
            <div class="row-li" style='padding: 0%'>
              <%= simple_format(@time_sheet.description) %>
            </div>
          </td>
        </tr>
      <% else %>

        <tr class="grey_background " style="  outline: 2px solid #ccc;">
          <td>
            <div id="start_container"  >
              <%= render 'time_sheets/finish_button', time: @time_sheet&.start_time, name: 'start_time' %>
            </div>

          </td>
          <td>
            <div class="field " id="finish_container">
              <%= render 'time_sheets/finish_button', time: @time_sheet&.finish_time, name: 'finish_time' %>

            </div>
          </td>
          <td>
            <div class="field ">
              <%= f.text_field :hour, min: 0, class: 'form-control hours-field', step: 0.01, placeholder: 'Hours' %>
            </div>
          </td>
          <%= f.hidden_field :time_period, value: params[:time_period] %>

          <%= f.hidden_field :project_id, value: params[:project_id] || @time_sheet.project.id %>

          <%= link_to "remove", time_sheet_path(@time_sheet), method: :delete, data: { confirm: 'Are you sure?' }, style: 'text-overflow:hidden' if @time_sheet.id? %>
          </div>
          </td>

          <td class="small-screen-hide">
            <%= image_tag('redcross.png', size: "40x40") if @time_sheet.id.present? %>
          </td>
        <tr>
          <td colspan="5" class="grey_background ">
            <div class="row-li " style='padding: 0%'>
              <%= f.text_area :description, cols: "60", rows: "1", class: 'form-control description-field', placeholder: 'Description' %>
            </div>
          </td>
        </tr>
      <% end %>

      </table>

  </table>
  <div style="width: 100%;position: relative;">
    <div class=" " style="margin-left: auto; margin-right: 0px;width: 270px">

      <% if @current_user.standard_workday.present? %>
        <% unless @time_sheet.invoice_id.present? %>
          <button type="button" onclick="set_standard_workday()" class="btn btn-default">
            <i class="fa fa-business-time"></i> Standard Workday
          </button>
        <% end %>
      <% else %>
        Configure standard work
        hours <%= link_to 'Here', current_user_path, style: 'color: blue;text-decoration: underline !important;' %>
      <% end %>
      <% unless @time_sheet.invoice_id.present? %>
        <%= button_tag :submit, class: 'btn btn-default' do %>
          <i class="fa fa-save"></i>
          Save
        <% end %>
      <% end %>
    </div>
  </div>

<% end %>

<style>
    body {
        position: relative;
    }

    .cell {
        flex-basis: 3000%;
        text-align: center;
        justify-content: center;
    }

    .field_with_errors {
        width: 100%;
    }
</style>


<script type="text/javascript" charset="utf-8">

    function set_standard_workday() {
        let start_time = '<%= @current_user.standard_workday&.start_time %>';
        let finish_time = '<%= @current_user.standard_workday&.finish_time %>';
        let time_period = '<%= params[:time_period] %>'
        let url = '<%= set_standard_work_hours_path() %>';
        $.get({
            url: url,
            data: {
                start_time: start_time,
                finish_time: finish_time,
                time_period: time_period
            },
            dataType: 'script'
        })


    }

    var start_var = document.getElementById('start_container');

    start_var.addEventListener("keydown", function (event) {
        // The parameter event is of the type KeyboardEvent
        event.preventDefault();
        return false;
    });

    var end_var = document.getElementById('finish_container');

    end_var.addEventListener("keydown", function (event) {
        // The parameter event is of the type KeyboardEvent
        event.preventDefault();
        return false;
    });


    $("#start_container").on(" mouseup ", function (e) {

        setTimeout(() => {
            setHours()
        }, 500);
    });
    $("#finish_container").on(" mouseup ", function (e) {
        setTimeout(() => {
            setHours()
        }, 500);
    });


    function setHours() {
        var start_time = document.getElementById("hidden-start_time")
        var finish_time = document.getElementById("hidden-finish_time")
        if (start_time && finish_time) {
            let startMoment = moment(start_time.value);
            let endMoment = moment(finish_time.value)
            let hours = moment.duration(endMoment.diff(startMoment))
            document.getElementById("time_sheet_work_day_hour").value = msToReadableTime(hours)
        }
    }

    function formatDD(dd) {
        return `0${dd}`.slice(-2);
    }

    function msToReadableTime(time) {
        const second = 1000;
        const minute = second * 60;
        const hour = minute * 60;
        let hours = Math.floor(time / hour % 24);
        let minutes = Math.floor(time / minute % 60);
        return formatDD(hours) + ':' + formatDD(minutes)
    }
</script>

app/views/time_sheets/_form_table.html.erb
<table class="outline table table-striped table-hover outline " style="  outline: 2px solid #ccc;">
  <tr class="grey_background " id="hours">
    <th style="width: 20%">Project</th>
    <th style="width: 20%">Start Time</th>
    <th style="width:20%">Finish Time</th>
    <th style="width: 20%">HH:MM</th>
    <th style="width: 20%"> Invoiced</th>
  </tr>
  <tr style="padding: 0;">
    <% if @time_sheet.invoice_id? %>

      <td colspan="5" class="clickable  " style="margin-bottom: 0px; outline: 2px solid #ccc;">
        <div class="row-li " style="display:flex; flex-direction: row" >
          <div class="cell">
            <%= @time_sheet.project.name %>
          </div>
          <div class="cell">
            <%= @time_sheet.start_time&.strftime('%d/%m/%y %I:%M  %p')|| 'Not Set' %>
          </div>
          <div class="cell">
            <%= @time_sheet.finish_time&.strftime('%d/%m/%y %I:%M  %p') || 'Not Set' %>
          </div>
          <div  class="cell">
            <%= @time_sheet.hour %>
          </div>
          <div class="cell">
            <%= image_tag('tick.png', size: "40x40") %>
          </div>
          <div class="field col-xs-11 col-sm-4" style='padding: 0%'>
            <%= @time_sheet.description %>
          </div>
          <div class="field col-xs-1 col-sm-1">
            <%= link_to "", invoice_path(@time_sheet.invoice_id) %>
          </div>
        </div>
      </td>
      </tr>
      <tr>
        <td colspan="4">
          <div class="row-li" style='padding: 0%'>
            <%= simple_format(@time_sheet.description) %>
          </div>
        </td>
      </tr>
    <% else %>
      <tr style="  outline: 2px solid #ccc;">
        <td>
          <div class=" " style="padding: 0%;width: 50px">
            <%= @time_sheet.project&.name %>
          </div>
        </td>
        <td>
          <div id="start-container" class=" " style="display: flex; flex-direction: row">
            <%= react_component("StartTimeButton", { name: 'time_sheet[start_time]', initial_time: @time_sheet.start_time, time_period: params[:time_period] ,id: 'start_time'}) %>
          </div>

        </td>
        <td>
          <div class="field " id="end-container">
            <%= react_component("StartTimeButton", { name: 'time_sheet[finish_time]', initial_time: @time_sheet.finish_time, time_period: params[:time_period],id: 'finish_time' }) %>

          </div>
        </td>
        <td>
          <div class="field ">
            <%= text_field_tag 'time_sheet[hour]', min: 0, class: 'form-control hours-field', style:"min-width: 70px", step: :any, placeholder: 'Hours', :autofocus => true %>
          </div>
        </td>
        <%= f.hidden_field :time_period, value: params[:time_period] %>
        <%= f.hidden_field :project_id, value: params[:project_id] %>
        <%= link_to "remove", time_sheet_path(@time_sheet), method: :delete, data: { confirm: 'Are you sure?' }, style: 'text-overflow:hidden' if @time_sheet.id? %>
        </div>
        </td>

        <td>
          <%= image_tag('redcross.png', size: "40x40") %>
        </td>
      <tr>
        <td colspan="5">
          <div class="row-li" style='padding: 0%'>
            <%= text_area_tag :description, cols: "60", rows: "1", class: 'form-control description-field', placeholder: 'Description' %>
          </div>
        </td>
      </tr>
    <% end %>

    <%#= f.fields_for :works do |builder| %>
    <%#= render 'works', f: builder %>
    <%# end %>

    </table>

app/views/time_sheets/_start_button.html.erb
<%= react_component("StartTimeButton",
                    props={ name: 'time_sheet_work_day[start_time]',
                            initial_time: time , time_period: params[:time_period] ,id: 'start_time'},
                    html_options={prerender: true}) %>

app/views/time_sheets/create.js.erb
$('#errors').html("<%= j render 'errors' %>")

app/views/time_sheets/edit.html.erb
<div style="min-width: 450px">
  <div class="box">
    <h1>User:  <%= @time_sheet.user.full_name %></h1>
    <h2>Date:   <%= @time_sheet&.time_period&.strftime("%d %A %B %Y") %></h2>
    <h2>Project: <%= @time_sheet&.project&.name %></h2>
  </div>
  <%= render 'days/buttons' %>
  <div class="box" >
    <div id="day_form" >
      <%= render 'time_sheets/form' %>
    </div>
    <!--  <div class="box"><h1>Travel</h1>-->
    <%#= content_tag :div, id: "vehicle_index", class: "time_sheet_class" do %>
    <!--      <script type="text/javascript" charset="utf-8">-->
    <!--          $.get({-->
    <!--              url: "<%#=  vehicles_path(time_period: params[:time_period],-->
<!--              project_id: params[:project_id]) %>",-->
    <!--              dataType: 'script'-->
    <!--          });-->

    <!--          $.get({-->
    <!--              url: "<%#=  travels_path(time_period: params[:time_period],project_id: params[:project_id])%>",-->
    <!--              dataType: 'script'-->
    <!--          })-->
    <!--      </script>-->
    <%# end %>
    <!--    <div id="travel_table"></div>-->
    <!--    <div id="travel_index"></div>-->

    <!--  </div>-->
  </div>
</div>

app/views/time_sheets/edit.js.erb
$('#form-table').html(<%= j render  'form_table' %>)

app/views/time_sheets/index.html.erb
<%# if can? :read, User %>
<%#= form_tag '', method: :get,  class: 'form-group row' do %>
<!--  <div class="col-lg-4">-->
<%#= select_tag(:user_id, options_for_select(User.select_attributes), class: ' btn btn-default form-control') %>
<!--  </div>-->
<%#= submit_tag 'Search', class: 'btn btn-default' %>
<%# end %>
<%# end %>

<% if @project.present? && @company.customers.present? && @company.name %>

  <%= my_calendar do |date| %>
    <%= date.strftime("%d  %b") %>
  <% end %>
<% else %>
  <div style="width: 100%;height:100%;position: relative">
    <div style="margin: auto; width: 350px;justify-content: center;position: relative;text-align: center">
       <div style="margin-left: auto; margin-right: auto"> <h1 >Before you begin</h1></div>
      <% unless @company.customers.present? %>
        <div>
          <%= link_to new_customer_path do %>
            <button type="button" class="btn btn-info onboard_button">Create Your First Customer</button>
          <% end %>
        </div>
      <% end %>
      <div>
        <%= link_to new_project_path do %>
          <button type="button" class="btn btn-info onboard_button">Create Your First Project</button>
        <% end %>
      </div>
      <% if @company.name.nil? && @current_user.has_role?(:admin) %>
        <%= link_to 'Set Company Name', edit_admin_company_path(current_user.company) ,class: 'btn btn-info onboard_button' %>
      <% end %>

    </div>
  </div>
<% end %>

<style>
    .onboard_button {
        width: 300px;
        margin: 10px;
    }
</style>

app/views/time_sheets/show.html.erb
<div class="box">
<p>
  <h1>Time Sheet for  <%= @time_sheet&.time_period&.strftime("%A %d %B %Y") %> Project <%= @project.name %></h1>
</p>
</div>
<%= render 'days/buttons' %>
<div id="time_sheet_partial" >
  <%= render 'edit' %>
<!--  <div class="box">-->
    <%#= render 'commits' rescue '' %>
<!--  </div>-->
</div>

app/views/time_sheets/update.js.erb
$('#errors').html("<%= j render 'errors' %>")