config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  namespace :admin do
    resources :invoice_configurations
    get 'dashboard', to: 'dashboard#index'
    get 'event_importer', to: 'event_importer#index'
    resources :companies, except: :index
    resources :projects
    authenticate(:user) do
      resources :users do
        resources :projects
        resources :identities
        resources :pay_rates
        resources :pay_obligations
        get :user_data
        get :user_income
        get :user_permission
        post :user_permission
      end
    end
  end
  scope :identities do
    resources :remote_calendars
  end
  get 'edit_standard_workday', to: 'standard_workdays#edit'
  resources :standard_workdays
  get '/set_standard_work_day', to: 'set_standard_work_day#standard_workdays'
  resources :companies, except: :index
  namespace :message_api do
    get 'chatrooms', to: 'chatrooms#get_chatrooms'
    post 'login', to: 'messages#login'
    post 'chatroom/:chatroom_id', to: 'messages#create'
    get 'chatroom/:chatroom_id', to: 'messages#show'
  end
  get '/home', to: 'landing_page#index'
  get '/change_password', to: 'users#change_password'
  get 'current_user', to: 'user#edit'
  patch 'current_user', to: 'user#update'
  resources :travels
  namespace :projects do
    get 'time_sheet_for_week/show'
  end
  resources :vehicles do
    '#my-container'
    resources :travels
  end
  resources :pay_rates
  resources :identities
  resources :projects do
    resources :invoices, except: [:edit], controller: 'projects/invoices'
  end
  resources :invoices, except: [:edit]
  resources :works
  get '/send_invoice', to: 'invoices#send_invoice', as: :send_invoice
  resources :social_info
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  resources :time_sheets, as: :time_sheet_work_days
  resources :time_sheets do
    resources :travels
    collection do
      post 'hours_for_day/:date', to: 'time_sheets#hours_for_day', as: '_hours'
    end
  end

  get '/current_day/:time_period', to: 'days#index', as: :current_day
  get '/set_standard_work_hours', to: 'days#set_standard_work_hours'
  resources :customers do
    get :details
  end

  resources :projects do
    collection do
      get :all_work_for_project
      get '/hours_by_day/:id/', to: 'projects#hours_by_day', as: :hours_by_day
      get '/hours_by_user_by/:id', to: 'projects#hours_by_user', as: :hours_by_user
      get '/:id/time_sheets_for_week(.:format)', to: 'projects#time_sheets_for_week', as: :time_sheets_for_week
      # resources :time_sheets_for_week
    end
  end

  mount ActionCable.server => '/cable'

  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions',
               omniauth_callbacks: 'users/omniauth_callbacks'
               # passwords: 'users/passwords'
             }
  get 'auth/:provider/callback', to: 'time_sheet#index'

  root to: 'time_sheets#index'
  # root to: "landing_page#index"
end

app/models/identity.rb
# frozen_string_literal: true

class Identity < Record
  belongs_to :user, dependent: :destroy
  include Defaults
  validates :uid, uniqueness: { message: 'already subscribed for another account' }
  has_one :remote_calendar

  # resourcify
end

app/controllers/identities_controller.rb
# frozen_string_literal: true

class IdentitiesController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_identity, only: %i[index show edit update destroy]
  before_action :authenticate_user!
  # load_and_authorize_resource
  # GET /identities
  # GET /identities.json
  def index
    @identities = Identity.where("user_id = '?'", current_user.id)
  end

  # GET /identities/1
  # GET /identities/1.json
  def show; end

  # GET /identities/new
  def new
    @user = User.from_omniauth(request.env['omniauth.auth'], current_user)
  end

  # GET /identities/1/edit
  def edit; end

  # POST /identities
  # POST /identities.json
  def create
    @identity = Identity.new(identity_params)

    respond_to do |format|
      if @identity.save
        format.html { redirect_to @identity, notice: 'Identity was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /identities/1
  # PATCH/PUT /identities/1.json
  def update
    respond_to do |format|
      if @identity.update(identity_params)
        format.html { redirect_to @identity, notice: 'Identity was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /identities/1
  # DELETE /identities/1.json
  def destroy

    @identity&.remote_calendar&.delete
    @identity.delete
    respond_to do |format|
      format.html { redirect_to identities_url, notice: 'Identity was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_identity
    @identity = Identity.find_by(user_id: current_user)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def identity_params
    params.require(:identity).permit(:provider, :username, :image, :user_id)
  end
end

app/helpers/identities_helper.rb
# frozen_string_literal: true

module IdentitiesHelper
end

app/views/identities/_form.html.erb
<div class="container-fluid">
  <div class="form-horizontal">
<%= form_for(identity) do |f| %>
  <% if identity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(identity.errors.count, "error") %> prohibited this identity from being saved:</h2>

      <ul>
      <% identity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="row">
      <div class="col-sm-2">
    <%= f.label :provider, class: "control-label" %>
      </div>
      <div class=" col-sm-7">
    <%= f.text_field :provider, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-sm-2">
    <%= f.label :image_url , class: "control-label"%>
      </div>
      <div class=" col-sm-7">
    <%= f.text_field :image , class: "form-control"%>
      </div>
    </div>
  </div>
  <div class="actions" style="width: 100%;text-align: right;margin-top: 20px;">
    <%= f.submit(class: 'btn btn-default')%>
  </div>
<% end %>
  </div>
</div>

app/views/identities/_identity.html.erb
<li class="shadow row >">

  <div class="col-sm-12"><strong><%= identity.username %></strong>
  <%= image_tag identity.image,size: 30 %>

<%= link_to 'Start Project', new_project_path(@identity), class: "btn btn-primary " %>
  </div>
</li>

app/views/identities/edit.html.erb
<h1>Editing Identity</h1>

<%= render 'form', identity: @identity %>

app/views/identities/index.html.erb
<h1>Identities</h1>

<table class="table">
  <thead>
    <tr>
      <th>Provider</th>
      <th>Username</th>
      <th>Image</th>
      <th width="300px"></th>
    </tr>
  </thead>

  <tbody>
    <% @identities.each do |iden| %>
      <tr>
        <td><%= iden.provider %></td>
        <td><%= iden.username %></td>
        <td><%= image_tag iden.image, size: 30 %></td>
        <td><%= link_to 'Show', iden , class: "btn btn-default" %>
        <%= link_to 'Edit', edit_identity_path(iden),class: "btn btn-default" %>
        <%= link_to 'Destroy', iden, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to  user_google_omniauth_authorize_path, class: 'btn btn-default ' do %>
  <span style="font-size: 16px;font-weight: bold">G</span>oogle
<% end %>
<%#= link_to 'acebook', '/admin/auth/facebook', class: 'btn btn-default fa fa-lg fa-facebook' %>
<%#= link_to ' GitHub', '/admin/auth/github', class: 'btn btn-default fa fa-lg fa-github' %>

app/views/identities/new.html.erb
<h1>New Identity</h1>

<%= render 'form', identity: @identity %>

app/views/identities/show.html.erb
<div class="box" style="position: relative;">
  <%= link_to 'Edit', edit_identity_path(@identity), class: 'btn btn-default',style: 'position: absolute; right: 5px;top: 5px '%>

<h2>
  <strong>Provider:</strong>
  <%= @identity.provider %>
</h2>

<p>
  <strong>Image:</strong>
  <%= image_tag @identity.image ,size: 30 %>
</p>

<div>
  <strong>Remote Calendar</strong>
    <%= react_component 'RemoteCalendar',{identity_id: @identity.id,default_calendar: {id: @identity&.remote_calendar&.id,remote_system_id: @identity&.remote_calendar&.remote_system_id,name: @identity&.remote_calendar&.name} } %>
</div>
</div>