config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  namespace :admin do
    resources :invoice_configurations
    get 'dashboard', to: 'dashboard#index'
    get 'event_importer', to: 'event_importer#index'
    resources :companies, except: :index
    resources :projects
    authenticate(:user) do
      resources :users do
        resources :projects
        resources :identities
        resources :pay_rates
        resources :pay_obligations
        get :user_data
        get :user_income
        get :user_permission
        post :user_permission
      end
    end
  end
  scope :identities do
    resources :remote_calendars
  end
  get 'edit_standard_workday', to: 'standard_workdays#edit'
  resources :standard_workdays
  get '/set_standard_work_day', to: 'set_standard_work_day#standard_workdays'
  resources :companies, except: :index
  namespace :message_api do
    get 'chatrooms', to: 'chatrooms#get_chatrooms'
    post 'login', to: 'messages#login'
    post 'chatroom/:chatroom_id', to: 'messages#create'
    get 'chatroom/:chatroom_id', to: 'messages#show'
  end
  get '/home', to: 'landing_page#index'
  get '/change_password', to: 'users#change_password'
  get 'current_user', to: 'user#edit'
  patch 'current_user', to: 'user#update'
  resources :travels
  namespace :projects do
    get 'time_sheet_for_week/show'
  end
  resources :vehicles do
    '#my-container'
    resources :travels
  end
  resources :pay_rates
  resources :identities
  resources :projects do
    resources :invoices, except: [:edit], controller: 'projects/invoices'
  end
  resources :invoices, except: [:edit]
  resources :works
  get '/send_invoice', to: 'invoices#send_invoice', as: :send_invoice
  resources :social_info
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  resources :time_sheets, as: :time_sheet_work_days
  resources :time_sheets do
    resources :travels
    collection do
      post 'hours_for_day/:date', to: 'time_sheets#hours_for_day', as: '_hours'
    end
  end

  get '/current_day/:time_period', to: 'days#index', as: :current_day
  get '/set_standard_work_hours', to: 'days#set_standard_work_hours'
  resources :customers do
    get :details
  end

  resources :projects do
    collection do
      get :all_work_for_project
      get '/hours_by_day/:id/', to: 'projects#hours_by_day', as: :hours_by_day
      get '/hours_by_user_by/:id', to: 'projects#hours_by_user', as: :hours_by_user
      get '/:id/time_sheets_for_week(.:format)', to: 'projects#time_sheets_for_week', as: :time_sheets_for_week
      # resources :time_sheets_for_week
    end
  end

  mount ActionCable.server => '/cable'

  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions',
               omniauth_callbacks: 'users/omniauth_callbacks'
               # passwords: 'users/passwords'
             }
  get 'auth/:provider/callback', to: 'time_sheet#index'

  root to: 'time_sheets#index'
  # root to: "landing_page#index"
end

app/models/standard_workday.rb
class StandardWorkday < Record
  include Defaults
  resourcify
  belongs_to :user
  belongs_to :company
end

app/controllers/standard_workdays_controller.rb
class StandardWorkdaysController < ApplicationController
  before_action :set_standard_workday, only: %i[show  update destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /standard_workdays or /standard_workdays.json
  def index
    @standard_workdays = StandardWorkday.where(user: @current_user)
  end

  # GET /standard_workdays/1 or /standard_workdays/1.json
  def show
  end

  # GET /standard_workdays/new
  def new
    @standard_workday = StandardWorkday.new
    respond_to do |format|
      format.js
    end
  end

  # GET /standard_workdays/1/edit
  def edit
    @standard_workday = StandardWorkday.find_or_initialize_by(user: @current_user)
    @time_period = params[:time_period]
    @start_time  = @current_user.standard_workday&.start_time
    @finish_time = @current_user.standard_workday&.finish_time
    respond_to do |format|
      format.js
    end
  end

  # POST /standard_workdays or /standard_workdays.json
  def create
    @standard_workday = StandardWorkday.new(standard_workday_params)
    @standard_workday.user = @current_user

    respond_to do |format|
      if @standard_workday.save
        format.html { redirect_to current_user_path, notice: "Standard workday was successfully created." }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /standard_workdays/1 or /standard_workdays/1.json
  def update
    respond_to do |format|
      if @standard_workday.update(standard_workday_params.merge(user_id: @current_user.id))
        format.html { redirect_to current_user_path}
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /standard_workdays/1 or /standard_workdays/1.json
  def destroy
    @standard_workday.destroy
    respond_to do |format|
      format.html { redirect_to standard_workdays_url, notice: "Standard workday was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_standard_workday
    @standard_workday = StandardWorkday.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def standard_workday_params
    params.require(:standard_workday).permit(:start_time, :finish_time)
  end
end

app/views/standard_workdays/_form.html.erb
<div class="box">
  <h1>Standard WorkDay</h1>
  <%= form_with(model: standard_workday, local: true, id: :standard_workday_form) do  %>
    <% if standard_workday.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(standard_workday.errors.count, "error") %> prohibited this standard_workday from being saved:</h2>

        <ul>
          <% standard_workday.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div>StartTime:  <%= react_component("StartTimeButton", props={ name: 'standard_workday[start_time]', initial_time: standard_workday&.start_time , id: 'start_time'}) %></div>
    <div>FinishTime:  <%= react_component("StartTimeButton", props={ name: 'standard_workday[finish_time]', initial_time: standard_workday&.finish_time , id: 'finish_time'}) %></div>
    <div class="actions">
      <button type="button" onclick="$('#standard_workday_form').submit()">Save</button>
    </div>
    </div>

  <% end %>

</div>
  <script type="text/javascript" charset="utf-8">

    function setHours(){
      return true
    }
  </script>

app/views/standard_workdays/edit.html.erb
<h1>Editing Standard Workday</h1>

<%= render 'form', standard_workday: @standard_workday %>

<%= link_to 'Show', @standard_workday %> |
<%= link_to 'Back', standard_workdays_path %>

app/views/standard_workdays/edit.js.erb
$('#standard-workday-form').html('  <%= j render 'standard_workdays/form',standard_workday: @standard_workday %>')
ReactRailsUJS.mountComponents()

app/views/standard_workdays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Standard Workdays</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @standard_workdays.each do |standard_workday| %>
      <tr>
        <td><%= link_to 'Show', standard_workday %></td>
        <td><%= link_to 'Edit', edit_standard_workday_path(standard_workday) %></td>
        <td><%= link_to 'Destroy', standard_workday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Standard Workday', new_standard_workday_path %>

app/views/standard_workdays/new.html.erb
<h1>New Standard Workday</h1>

<%= render 'form', standard_workday: @standard_workday %>

<%= link_to 'Back', standard_workdays_path %>

app/views/standard_workdays/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_standard_workday_path(@standard_workday) %> |
<%= link_to 'Back', standard_workdays_path %>